In [1]:
import pandas as pd

file = r"C:\Users\sujee\Desktop\spark_input\stack-overflow-developer-survey-2019"

df = pd.read_csv(file+r"\survey_results_public.csv", index_col='Respondent')

df_schema = pd.read_csv(file+r"\survey_results_schema.csv",index_col='Column')

In [2]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [3]:
df.shape

(88883, 84)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 88883 entries, 1 to 88863
Data columns (total 84 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MainBranch              88331 non-null  object
 1   Hobbyist                88883 non-null  object
 2   OpenSourcer             88883 non-null  object
 3   OpenSource              86842 non-null  object
 4   Employment              87181 non-null  object
 5   Country                 88751 non-null  object
 6   Student                 87014 non-null  object
 7   EdLevel                 86390 non-null  object
 8   UndergradMajor          75614 non-null  object
 9   EduOther                84260 non-null  object
 10  OrgSize                 71791 non-null  object
 11  DevType                 81335 non-null  object
 12  YearsCode               87938 non-null  object
 13  Age1stCode              87634 non-null  object
 14  YearsCodePro            74331 non-null  object
 15  CareerSat               72847 non-null  object
 16  JobSat                  70988 non-null  object
 17  MgrIdiot                61159 non-null  object
 18  MgrMoney                61157 non-null  object
 19  MgrWant                 61232 non-null  object
 20  JobSeek                 80555 non-null  object
 21  LastHireDate            79854 non-null  object
 22  LastInt                 67155 non-null  object
 23  FizzBuzz                71344 non-null  object
 24  JobFactors              79371 non-null  object
 25  ResumeUpdate            77877 non-null  object
 26  CurrencySymbol          71392 non-null  object
 27  CurrencyDesc            71392 non-null  object
 28  CompTotal               55945 non-null  float64
 29  CompFreq                63268 non-null  object
 30  ConvertedComp           55823 non-null  float64
 31  WorkWeekHrs             64503 non-null  float64
 32  WorkPlan                68914 non-null  object
 33  WorkChallenge           68141 non-null  object
 34  WorkRemote              70284 non-null  object
 35  WorkLoc                 70055 non-null  object
 36  ImpSyn                  71779 non-null  object
 37  CodeRev                 70390 non-null  object
 38  CodeRevHrs              49790 non-null  float64
 39  UnitTests               62668 non-null  object
 40  PurchaseHow             61108 non-null  object
 41  PurchaseWhat            62029 non-null  object
 42  LanguageWorkedWith      87569 non-null  object
 43  LanguageDesireNextYear  84088 non-null  object
 44  DatabaseWorkedWith      76026 non-null  object
 45  DatabaseDesireNextYear  69147 non-null  object
 46  PlatformWorkedWith      80714 non-null  object
 47  PlatformDesireNextYear  77443 non-null  object
 48  WebFrameWorkedWith      65022 non-null  object
 49  WebFrameDesireNextYear  62944 non-null  object
 50  MiscTechWorkedWith      59586 non-null  object
 51  MiscTechDesireNextYear  64511 non-null  object
 52  DevEnviron              87317 non-null  object
 53  OpSys                   87851 non-null  object
 54  Containers              85366 non-null  object
 55  BlockchainOrg           48175 non-null  object
 56  BlockchainIs            60165 non-null  object
 57  BetterLife              86269 non-null  object
 58  ITperson                87141 non-null  object
 59  OffOn                   86663 non-null  object
 60  SocialMedia             84437 non-null  object
 61  Extraversion            87305 non-null  object
 62  ScreenName              80486 non-null  object
 63  SOVisit1st              83877 non-null  object
 64  SOVisitFreq             88263 non-null  object
 65  SOVisitTo               88086 non-null  object
 66  SOFindAnswer            87816 non-null  object
 67  SOTimeSaved             86344 non-null  object
 68  SOHowMuchTime           68378 non-null  object
 69  SOAccount               87828 non-null  object
 70  SOPartFreq              74692 non-null  object
 71  SOJobs                  88066 non-null  object
 72  EntTeams                87841 non-null  object
 73  SOComm                  88131 non-null  object
 74  WelcomeChange           85855 non-null  object
 75  SONewContent            69560 non-null  object
 76  Age                     79210 non-null  float64
 77  Gender                  85406 non-null  object
 78  Trans                   83607 non-null  object
 79  Sexuality               76147 non-null  object
 80  Ethnicity               76668 non-null  object
 81  Dependents              83059 non-null  object
 82  SurveyLength            86984 non-null  object
 83  SurveyEase              87081 non-null  object
dtypes: float64(5), object(79)
memory usage: 57.6+ MB

In [5]:
df.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [6]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [7]:
df_schema

                                                             QuestionText
Column
Respondent              Randomized respondent ID number (not in order ...
MainBranch              Which of the following options best describes ...
Hobbyist                                          Do you code as a hobby?
OpenSourcer                   How often do you contribute to open source?
OpenSource              How do you feel about the quality of open sour...
Employment              Which of the following best describes your cur...
Country                         In which country do you currently reside?
Student                 Are you currently enrolled in a formal, degree...
EdLevel                 Which of the following best describes the high...
UndergradMajor          What was your main or most important field of ...
EduOther                Which of the following types of non-degree edu...
OrgSize                 Approximately how many people are employed by ...
DevType                 Which of the following describe you? Please se...
YearsCode               Including any education, how many years have y...
Age1stCode              At what age did you write your first line of c...
YearsCodePro            How many years have you coded professionally (...
CareerSat               Overall, how satisfied are you with your caree...
JobSat                  How satisfied are you with your current job? (...
MgrIdiot                How confident are you that your manager knows ...
MgrMoney                Do you believe that you need to be a manager t...
MgrWant                 Do you want to become a manager yourself in th...
JobSeek                 Which of the following best describes your cur...
LastHireDate            When was the last time that you took a job wit...
LastInt                 In your most recent successful job interview (...
FizzBuzz                Have you ever been asked to solve FizzBuzz in ...
JobFactors              Imagine that you are deciding between two job ...
ResumeUpdate            Think back to the last time you updated your r...
CurrencySymbol          Which currency do you use day-to-day? If your ...
CurrencyDesc            Which currency do you use day-to-day? If your ...
CompTotal               What is your current total compensation (salar...
CompFreq                 Is that compensation weekly, monthly, or yearly?
ConvertedComp           Salary converted to annual USD salaries using ...
WorkWeekHrs              On average, how many hours per week do you work?
WorkPlan                          How structured or planned is your work?
WorkChallenge           Of these options, what are your greatest chall...
WorkRemote                                How often do you work remotely?
WorkLoc                                   Where would you prefer to work?
ImpSyn                  For the specific work you do, and the years of...
CodeRev                          Do you review code as part of your work?
CodeRevHrs              On average, how many hours per week do you spe...
UnitTests               Does your company regularly employ unit tests ...
PurchaseHow             How does your company make decisions about pur...
PurchaseWhat            What level of influence do you, personally, ha...
LanguageWorkedWith      Which of the following programming, scripting,...
LanguageDesireNextYear  Which of the following programming, scripting,...
DatabaseWorkedWith      Which of the following database environments h...
DatabaseDesireNextYear  Which of the following database environments h...
PlatformWorkedWith      Which of the following platforms have you done...
PlatformDesireNextYear  Which of the following platforms have you done...
WebFrameWorkedWith      Which of the following web frameworks have you...
WebFrameDesireNextYear  Which of the following web frameworks have you...
MiscTechWorkedWith      Which of the following other frameworks, libra...
MiscTechDesireNextYear  Which of the following other frameworks, libra...
DevEnviron              Which development environment(s) do you use re...
OpSys                   What is the primary operating system in which ...
Containers              How do you use containers (Docker, Open Contai...
BlockchainOrg           How is your organization thinking about or imp...
BlockchainIs            Blockchain / cryptocurrency technology is prim...
BetterLife              Do you think people born today will have a bet...
ITperson                 Are you the "IT support person" for your family?
OffOn                         Have you tried turning it off and on again?
SocialMedia                   What social media site do you use the most?
Extraversion              Do you prefer online chat or IRL conversations?
ScreenName                                           What do you call it?
SOVisit1st              To the best of your memory, when did you first...
SOVisitFreq             How frequently would you say you visit Stack O...
SOVisitTo               I visit Stack Overflow to... (check all that a...
SOFindAnswer            On average, how many times a week do you find ...
SOTimeSaved             Think back to the last time you solved a codin...
SOHowMuchTime           About how much time did you save? If you're no...
SOAccount                           Do you have a Stack Overflow account?
SOPartFreq              How frequently would you say you participate i...
SOJobs                  Have you ever used or visited Stack Overflow J...
EntTeams                Have you ever used Stack Overflow for Enterpri...
SOComm                  Do you consider yourself a member of the Stack...
WelcomeChange           Compared to last year, how welcome do you feel...
SONewContent            Would you like to see any of the following on ...
Age                     What is your age (in years)? If you prefer not...
Gender                  Which of the following do you currently identi...
Trans                                     Do you identify as transgender?
Sexuality               Which of the following do you currently identi...
Ethnicity               Which of the following do you identify as? Ple...
Dependents              Do you have any dependents (e.g., children, el...
SurveyLength            How do you feel about the length of the survey...
SurveyEase              How easy or difficult was this survey to compl...

In [8]:
df.tail(5)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [82]:
person = {
    "first" : "sujeet",
    "last": "singh",
    "email": "sujeet.kumar@abc.com"
}



people ={
    
    "first" : ["sujeet",'Ramesh'],
    "last": ["singh",'kumar'],
    "email": ["sujeet.kumar@abc.com", 'ramesh@gmail.com']
    
}


people_df = pd.DataFrame(people)

people_df

    first   last                 email
0  sujeet  singh  sujeet.kumar@abc.com
1  Ramesh  kumar      ramesh@gmail.com

In [10]:
type(people_df)

pandas.core.frame.DataFrame

In [11]:
people_df['email']

0    sujeet.kumar@abc.com
1        ramesh@gmail.com
Name: email, dtype: object

In [12]:
type(people_df['email'])

pandas.core.series.Series

In [13]:
people_df.email

0    sujeet.kumar@abc.com
1        ramesh@gmail.com
Name: email, dtype: object

In [14]:
people_df[['email','first']]   #passing a list of column to access multiple column and no longer 
                                #be series(b/c single column in row

                  email   first
0  sujeet.kumar@abc.com  sujeet
1      ramesh@gmail.com  Ramesh

In [15]:
type(people_df[['email','first']]  )

pandas.core.frame.DataFrame

In [16]:
people_df.columns

Index(['first', 'last', 'email'], dtype='object')

In [17]:
#how to get row

#loc
#iloc


print(type(people_df.iloc[0]))

people_df.iloc[0]

<class 'pandas.core.series.Series'>

first                  sujeet
last                    singh
email    sujeet.kumar@abc.com
Name: 0, dtype: object

In [18]:
people_df.iloc[[0,1]]

    first   last                 email
0  sujeet  singh  sujeet.kumar@abc.com
1  Ramesh  kumar      ramesh@gmail.com

In [19]:
people_df.iloc[[0,1], [2]] #list of row and second list is column

                  email
0  sujeet.kumar@abc.com
1      ramesh@gmail.com

In [20]:
people_df

    first   last                 email
0  sujeet  singh  sujeet.kumar@abc.com
1  Ramesh  kumar      ramesh@gmail.com

In [21]:
people_df.loc[0]

first                  sujeet
last                    singh
email    sujeet.kumar@abc.com
Name: 0, dtype: object

In [22]:
people_df.loc[[0,1]]

    first   last                 email
0  sujeet  singh  sujeet.kumar@abc.com
1  Ramesh  kumar      ramesh@gmail.com

In [23]:
people_df.loc[[0,1],['email']]

                  email
0  sujeet.kumar@abc.com
1      ramesh@gmail.com

In [24]:
df.columns

Index(['MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource', 'Employment',
       'Country', 'Student', 'EdLevel', 'UndergradMajor', 'EduOther',
       'OrgSize', 'DevType', 'YearsCode', 'Age1stCode', 'YearsCodePro',
       'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney', 'MgrWant', 'JobSeek',
       'LastHireDate', 'LastInt', 'FizzBuzz', 'JobFactors', 'ResumeUpdate',
       'CurrencySymbol', 'CurrencyDesc', 'CompTotal', 'CompFreq',
       'ConvertedComp', 'WorkWeekHrs', 'WorkPlan', 'WorkChallenge',
       'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev', 'CodeRevHrs', 'UnitTests',
       'PurchaseHow', 'PurchaseWhat', 'LanguageWorkedWith',
       'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [25]:
df['Hobbyist']

Respondent
1        Yes
2         No
3        Yes
4         No
5        Yes
        ...
88377    Yes
88601     No
88802     No
88816     No
88863    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [26]:
df.loc[0,'Hobbyist']

KeyError: 0

In [ ]:
df.loc[0:2, 'Hobbyist':'Employment']

In [ ]:
people_df

In [ ]:
#set index 

people_df.set_index('email',inplace=True)

print(people_df.loc['ramesh@gmail.com'])

In [ ]:
people_df.index

In [ ]:
people_df.reset_index(inplace=True)

people_df

In [ ]:
df_schema.loc['Hobbyist']

In [ ]:
df_schema.sort_index(ascending=False)

In [ ]:
people_df.reset_index(inplace=True)
print(people_df.index)

In [ ]:

first =(people_df['first'] == 'sujeet') | (people_df['first'] == 'Ramesh') 

print(first)
people_df.loc[first]

In [ ]:
df_schema

In [ ]:
high_sal = (df['ConvertedComp'] > 70000)

df.loc(high_sal,['ConvertedComp','DevType'])

In [ ]:
import pandas as pd
import numpy as np


def read_file():
    path = r"C:\Users\sujee\Desktop\spark_input\stack-overflow-developer-survey-2019"
    df = pd.read_csv(path + r"\survey_results_public.csv", index_col='Respondent')
    df_schema = pd.read_csv(path + r"\survey_results_schema.csv", index_col='Column')
    pd.set_option('display.max_columns', 85)
    pd.set_option('display.max_rows', 85)

    return df, df_schema



df_schema

In [ ]:
df, df_schema = read_file()
country = ['India', 'Germany', 'Canada']
high_sal = (df['ConvertedComp'] > 70000) & (df['Country'].isin(country)) \
      & (df['LanguageWorkedWith'].str.contains('Python', na=False))

In [ ]:
df.loc[high_sal,['Country','LanguageWorkedWith','ConvertedComp']]

In [28]:
people_df

people_df.columns = [i.upper() for i in people_df.columns]

people_df.columns = people_df.columns.str.replace(' ','_')

people_df

    FIRST   LAST                 EMAIL
0  sujeet  singh  sujeet.kumar@abc.com
1  Ramesh  kumar      ramesh@gmail.com

In [35]:
people_df.rename(columns={'FIRST':'first_name','LAST':'last_name','EMAIL':'email'},inplace=True)

In [37]:
people_df

  first_name last_name                 email
0     sujeet     singh  sujeet.kumar@abc.com
1     Ramesh     kumar      ramesh@gmail.com

In [40]:
people_df.loc[1]

first_name              Ramesh
last_name                kumar
email         ramesh@gmail.com
Name: 1, dtype: object

In [41]:
people_df.loc[1] = ['John','smith','john@gmail.com']

In [44]:
people_df

  first_name last_name                 email
0     sujeet     singh  sujeet.kumar@abc.com
1       John     smith        john@gmail.com

In [47]:
people_df.loc[2, ['last_name','email']] = ['Doe','JohnDoe@email.com']

In [54]:
people_df

  first_name last_name                 email last
0     sujeet     singh  sujeet.kumar@abc.com  NaN
1       John     smith        john@gmail.com  NaN
2        NaN       Doe     JohnDoe@email.com  Doe

In [55]:
people_df.at[2,'first_name'] = 'Correy'

In [56]:
people_df

  first_name last_name                 email last
0     sujeet     singh  sujeet.kumar@abc.com  NaN
1       John     smith        john@gmail.com  NaN
2     Correy       Doe     JohnDoe@email.com  Doe

In [65]:
people_df['email'].apply(len)

0    20
1    14
2    17
Name: email, dtype: int64

In [66]:
def update_email(e):
    return e.upper()

people_df['email']=people_df['email'].apply(update_email)


people_df

  first_name last_name                 email last
0     sujeet     singh  SUJEET.KUMAR@ABC.COM  NaN
1       John     smith        JOHN@GMAIL.COM  NaN
2     Correy       Doe     JOHNDOE@EMAIL.COM  Doe

In [83]:
#people_df.rename(columns={'last':'full_name'}, inplace=True)

people_df['full_name']=people_df['first'] + ' ' + people_df['last']

In [84]:
people_df

    first   last                 email     full_name
0  sujeet  singh  sujeet.kumar@abc.com  sujeet singh
1  Ramesh  kumar      ramesh@gmail.com  Ramesh kumar

In [87]:
people_df.applymap(str.upper)

    first   last                 email     full_name
0  SUJEET  SINGH  SUJEET.KUMAR@ABC.COM  SUJEET SINGH
1  RAMESH  KUMAR      RAMESH@GMAIL.COM  RAMESH KUMAR

In [89]:
people_df['first'].map(str.lower)

0    sujeet
1    ramesh
Name: first, dtype: object

In [92]:
people_df.drop(index=people_df[people_df['last'] == 'kumar'].index)

    first   last                 email     full_name
0  sujeet  singh  sujeet.kumar@abc.com  sujeet singh